export interface ApostilleStateInfo {
  state: string;
  abbreviation: string;
  sosName: string;
  sosAddress: string;
  sosPhone: string;
  sosEmail: string;
  fee: number;
  processingDays: string;
  acceptsElectronic: boolean;
  walkInAvailable: boolean;
  notes: string;
}

export const apostilleStateData: ApostilleStateInfo[] = [
  { state: "Alabama", abbreviation: "AL", sosName: "Alabama Secretary of State", sosAddress: "PO Box 5616, Montgomery, AL 36103", sosPhone: "(334) 242-7200", sosEmail: "sos@sos.alabama.gov", fee: 10, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Mail-in and walk-in. Notarized docs only." },
  { state: "Alaska", abbreviation: "AK", sosName: "Alaska Lt. Governor's Office", sosAddress: "PO Box 110015, Juneau, AK 99811", sosPhone: "(907) 465-3520", sosEmail: "ltgov@alaska.gov", fee: 25, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Notarized documents and vital records." },
  { state: "Arizona", abbreviation: "AZ", sosName: "Arizona Secretary of State", sosAddress: "1700 W Washington St, Phoenix, AZ 85007", sosPhone: "(602) 542-6187", sosEmail: "azsos@azsos.gov", fee: 10, processingDays: "3-5", acceptsElectronic: true, walkInAvailable: true, notes: "Expedited same-day available for walk-in." },
  { state: "Arkansas", abbreviation: "AR", sosName: "Arkansas Secretary of State", sosAddress: "State Capitol, Little Rock, AR 72201", sosPhone: "(501) 682-1010", sosEmail: "info@sos.arkansas.gov", fee: 10, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Mail-in preferred." },
  { state: "California", abbreviation: "CA", sosName: "California Secretary of State", sosAddress: "1500 11th St, Sacramento, CA 95814", sosPhone: "(916) 653-3595", sosEmail: "notaryinfo@sos.ca.gov", fee: 26, processingDays: "5-10", acceptsElectronic: true, walkInAvailable: true, notes: "High volume. Prepaid return envelope required for mail." },
  { state: "Colorado", abbreviation: "CO", sosName: "Colorado Secretary of State", sosAddress: "1700 Broadway, Ste 550, Denver, CO 80290", sosPhone: "(303) 894-2200", sosEmail: "sos@sos.state.co.us", fee: 10, processingDays: "3-5", acceptsElectronic: true, walkInAvailable: true, notes: "Online submission available." },
  { state: "Connecticut", abbreviation: "CT", sosName: "Connecticut Secretary of State", sosAddress: "165 Capitol Ave, Hartford, CT 06106", sosPhone: "(860) 509-6200", sosEmail: "sots@ct.gov", fee: 20, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in same-day service." },
  { state: "Delaware", abbreviation: "DE", sosName: "Delaware Secretary of State", sosAddress: "401 Federal St, Dover, DE 19901", sosPhone: "(302) 739-4111", sosEmail: "dos@delaware.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Rush service available." },
  { state: "Florida", abbreviation: "FL", sosName: "Florida Secretary of State", sosAddress: "500 S Bronough St, Tallahassee, FL 32399", sosPhone: "(850) 245-6500", sosEmail: "notaries@dos.myflorida.com", fee: 10, processingDays: "5-10", acceptsElectronic: true, walkInAvailable: true, notes: "E-apostille available for some documents." },
  { state: "Georgia", abbreviation: "GA", sosName: "Georgia Superior Court Clerks", sosAddress: "244 Washington St, Atlanta, GA 30334", sosPhone: "(404) 327-6023", sosEmail: "gsccca@gsccca.org", fee: 3, processingDays: "3-5", acceptsElectronic: true, walkInAvailable: true, notes: "Lowest fee in the nation." },
  { state: "Hawaii", abbreviation: "HI", sosName: "Hawaii Lt. Governor's Office", sosAddress: "State Capitol, Honolulu, HI 96813", sosPhone: "(808) 586-0255", sosEmail: "ltgov@hawaii.gov", fee: 10, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Limited walk-in hours." },
  { state: "Idaho", abbreviation: "ID", sosName: "Idaho Secretary of State", sosAddress: "PO Box 83720, Boise, ID 83720", sosPhone: "(208) 334-2300", sosEmail: "sosinfo@sos.idaho.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Illinois", abbreviation: "IL", sosName: "Illinois Secretary of State", sosAddress: "111 E Monroe St, Springfield, IL 62756", sosPhone: "(217) 782-2201", sosEmail: "departments@ilsos.net", fee: 2, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Very low fee." },
  { state: "Indiana", abbreviation: "IN", sosName: "Indiana Secretary of State", sosAddress: "200 W Washington St, Indianapolis, IN 46204", sosPhone: "(317) 232-6531", sosEmail: "sos@sos.in.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in and mail-in." },
  { state: "Iowa", abbreviation: "IA", sosName: "Iowa Secretary of State", sosAddress: "321 E 12th St, Des Moines, IA 50319", sosPhone: "(515) 281-5204", sosEmail: "sos@sos.iowa.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Kansas", abbreviation: "KS", sosName: "Kansas Secretary of State", sosAddress: "120 SW 10th Ave, Topeka, KS 66612", sosPhone: "(785) 296-4564", sosEmail: "kssos@ks.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in preferred." },
  { state: "Kentucky", abbreviation: "KY", sosName: "Kentucky Secretary of State", sosAddress: "700 Capital Ave, Frankfort, KY 40601", sosPhone: "(502) 564-3490", sosEmail: "sos.secretary@ky.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Louisiana", abbreviation: "LA", sosName: "Louisiana Secretary of State", sosAddress: "PO Box 94125, Baton Rouge, LA 70804", sosPhone: "(225) 922-2880", sosEmail: "admin@sos.la.gov", fee: 15, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Mail and walk-in." },
  { state: "Maine", abbreviation: "ME", sosName: "Maine Secretary of State", sosAddress: "148 State House Station, Augusta, ME 04333", sosPhone: "(207) 626-8400", sosEmail: "sos.office@maine.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Maryland", abbreviation: "MD", sosName: "Maryland Secretary of State", sosAddress: "16 Francis St, Annapolis, MD 21401", sosPhone: "(410) 974-5521", sosEmail: "dlnotary_sos@maryland.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in same-day available." },
  { state: "Massachusetts", abbreviation: "MA", sosName: "Massachusetts Secretary of the Commonwealth", sosAddress: "One Ashburton Pl, Boston, MA 02108", sosPhone: "(617) 727-9180", sosEmail: "cis@sec.state.ma.us", fee: 12, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in and mail." },
  { state: "Michigan", abbreviation: "MI", sosName: "Michigan Secretary of State", sosAddress: "430 W Allegan St, Lansing, MI 48918", sosPhone: "(517) 322-1460", sosEmail: "sos-info@michigan.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Minnesota", abbreviation: "MN", sosName: "Minnesota Secretary of State", sosAddress: "180 State Office Building, St. Paul, MN 55155", sosPhone: "(651) 296-2803", sosEmail: "secretary.state@state.mn.us", fee: 10, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Mail-in preferred." },
  { state: "Mississippi", abbreviation: "MS", sosName: "Mississippi Secretary of State", sosAddress: "PO Box 136, Jackson, MS 39205", sosPhone: "(601) 359-1350", sosEmail: "admin@sos.ms.gov", fee: 10, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Missouri", abbreviation: "MO", sosName: "Missouri Secretary of State", sosAddress: "600 W Main St, Jefferson City, MO 65101", sosPhone: "(573) 751-4936", sosEmail: "sosmain@sos.mo.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in and mail." },
  { state: "Montana", abbreviation: "MT", sosName: "Montana Secretary of State", sosAddress: "PO Box 202801, Helena, MT 59620", sosPhone: "(406) 444-2034", sosEmail: "sos@mt.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Nebraska", abbreviation: "NE", sosName: "Nebraska Secretary of State", sosAddress: "PO Box 94608, Lincoln, NE 68509", sosPhone: "(402) 471-2554", sosEmail: "sos.notary@nebraska.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Nevada", abbreviation: "NV", sosName: "Nevada Secretary of State", sosAddress: "101 N Carson St, Carson City, NV 89701", sosPhone: "(775) 684-5708", sosEmail: "sosmail@sos.nv.gov", fee: 20, processingDays: "3-5", acceptsElectronic: true, walkInAvailable: true, notes: "Rush service available." },
  { state: "New Hampshire", abbreviation: "NH", sosName: "New Hampshire Secretary of State", sosAddress: "25 Capitol St, Concord, NH 03301", sosPhone: "(603) 271-3242", sosEmail: "elections@sos.nh.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "New Jersey", abbreviation: "NJ", sosName: "New Jersey Department of Treasury", sosAddress: "PO Box 628, Trenton, NJ 08646", sosPhone: "(609) 292-9292", sosEmail: "apostille@sos.nj.gov", fee: 10, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "High volume state." },
  { state: "New Mexico", abbreviation: "NM", sosName: "New Mexico Secretary of State", sosAddress: "325 Don Gaspar, Santa Fe, NM 87501", sosPhone: "(505) 827-3600", sosEmail: "sos.elections@state.nm.us", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "New York", abbreviation: "NY", sosName: "New York Department of State", sosAddress: "One Commerce Plaza, Albany, NY 12231", sosPhone: "(518) 474-4750", sosEmail: "info@dos.ny.gov", fee: 10, processingDays: "5-10", acceptsElectronic: true, walkInAvailable: true, notes: "County clerk authentication may also be required." },
  { state: "North Carolina", abbreviation: "NC", sosName: "North Carolina Secretary of State", sosAddress: "PO Box 29622, Raleigh, NC 27626", sosPhone: "(919) 814-5400", sosEmail: "authentications@sosnc.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in same-day." },
  { state: "North Dakota", abbreviation: "ND", sosName: "North Dakota Secretary of State", sosAddress: "600 E Boulevard Ave, Bismarck, ND 58505", sosPhone: "(701) 328-2900", sosEmail: "sos@nd.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Ohio", abbreviation: "OH", sosName: "Ohio Secretary of State", sosAddress: "180 E Broad St, Columbus, OH 43215", sosPhone: "(614) 466-2655", sosEmail: "apostille@ohiosos.gov", fee: 10, processingDays: "3-5", acceptsElectronic: true, walkInAvailable: true, notes: "ORC §147 compliant. Walk-in same-day available. E-apostille program active." },
  { state: "Oklahoma", abbreviation: "OK", sosName: "Oklahoma Secretary of State", sosAddress: "2300 N Lincoln Blvd, Oklahoma City, OK 73105", sosPhone: "(405) 521-3912", sosEmail: "info@sos.ok.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Oregon", abbreviation: "OR", sosName: "Oregon Secretary of State", sosAddress: "255 Capitol St NE, Salem, OR 97310", sosPhone: "(503) 986-2200", sosEmail: "oregon.sos@sos.oregon.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Mail and walk-in." },
  { state: "Pennsylvania", abbreviation: "PA", sosName: "Pennsylvania Department of State", sosAddress: "302 North Office Building, Harrisburg, PA 17120", sosPhone: "(717) 787-6458", sosEmail: "ra-bcel@pa.gov", fee: 15, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Requires prior notarization." },
  { state: "Rhode Island", abbreviation: "RI", sosName: "Rhode Island Secretary of State", sosAddress: "148 W River St, Providence, RI 02904", sosPhone: "(401) 222-2357", sosEmail: "sosgeneral@sos.ri.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "South Carolina", abbreviation: "SC", sosName: "South Carolina Secretary of State", sosAddress: "1205 Pendleton St, Columbia, SC 29201", sosPhone: "(803) 734-2170", sosEmail: "info@sos.sc.gov", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "South Dakota", abbreviation: "SD", sosName: "South Dakota Secretary of State", sosAddress: "500 E Capitol Ave, Pierre, SD 57501", sosPhone: "(605) 773-3537", sosEmail: "sdsos@state.sd.us", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Tennessee", abbreviation: "TN", sosName: "Tennessee Secretary of State", sosAddress: "312 Rosa L. Parks Ave, Nashville, TN 37243", sosPhone: "(615) 741-2816", sosEmail: "sos.info@tn.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Walk-in and mail." },
  { state: "Texas", abbreviation: "TX", sosName: "Texas Secretary of State", sosAddress: "PO Box 12887, Austin, TX 78711", sosPhone: "(512) 463-5555", sosEmail: "notary@sos.texas.gov", fee: 15, processingDays: "5-10", acceptsElectronic: true, walkInAvailable: true, notes: "High volume. Online submission available." },
  { state: "Utah", abbreviation: "UT", sosName: "Utah Lt. Governor's Office", sosAddress: "PO Box 142325, Salt Lake City, UT 84114", sosPhone: "(801) 538-1041", sosEmail: "notary@utah.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Vermont", abbreviation: "VT", sosName: "Vermont Secretary of State", sosAddress: "128 State St, Montpelier, VT 05633", sosPhone: "(802) 828-2363", sosEmail: "sos@sec.state.vt.us", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Virginia", abbreviation: "VA", sosName: "Virginia Secretary of the Commonwealth", sosAddress: "1111 E Broad St, Richmond, VA 23219", sosPhone: "(804) 786-2441", sosEmail: "apostilles@governor.virginia.gov", fee: 10, processingDays: "3-5", acceptsElectronic: true, walkInAvailable: true, notes: "E-apostille available." },
  { state: "Washington", abbreviation: "WA", sosName: "Washington Secretary of State", sosAddress: "PO Box 40220, Olympia, WA 98504", sosPhone: "(360) 902-4151", sosEmail: "sos@sos.wa.gov", fee: 15, processingDays: "5-10", acceptsElectronic: true, walkInAvailable: true, notes: "Online submission via MyApostille." },
  { state: "West Virginia", abbreviation: "WV", sosName: "West Virginia Secretary of State", sosAddress: "Building 1, Suite 157-K, Charleston, WV 25305", sosPhone: "(304) 558-6000", sosEmail: "wvsos@wvsos.com", fee: 10, processingDays: "5-7", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Wisconsin", abbreviation: "WI", sosName: "Wisconsin Secretary of State", sosAddress: "PO Box 7848, Madison, WI 53707", sosPhone: "(608) 266-8888", sosEmail: "statesec@wi.gov", fee: 10, processingDays: "5-10", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "Wyoming", abbreviation: "WY", sosName: "Wyoming Secretary of State", sosAddress: "2020 Carey Ave, Cheyenne, WY 82002", sosPhone: "(307) 777-7378", sosEmail: "sos@wyo.gov", fee: 10, processingDays: "3-5", acceptsElectronic: false, walkInAvailable: true, notes: "Standard processing." },
  { state: "District of Columbia", abbreviation: "DC", sosName: "DC Secretary of State", sosAddress: "1350 Pennsylvania Ave NW, Washington, DC 20004", sosPhone: "(202) 727-6306", sosEmail: "os.apostille@dc.gov", fee: 10, processingDays: "3-5", acceptsElectronic: true, walkInAvailable: true, notes: "Walk-in same-day service available." },
];
