export interface DocumentTemplate {
  id: string;
  name: string;
  category: string;
  description: string;
  html: string;
  placeholders: string[];
}

const DISCLAIMER = `<p style="margin-top:24px;font-size:9px;color:#888;border-top:1px solid #ddd;padding-top:8px;">
  <em>This document was generated for informational purposes only. It does not constitute legal advice. 
  Consult a licensed attorney for legal matters. Generated by Notar Enterprise Tools.</em>
</p>`;

export const documentTemplates: Record<string, DocumentTemplate> = {
  acknowledgment: {
    id: "acknowledgment",
    name: "Acknowledgment Certificate",
    category: "Notarial Certificates",
    description: "Standard acknowledgment certificate per ORC §147.55",
    placeholders: ["state", "county", "date", "signer_name", "notary_name", "commission_number", "commission_expiration"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">ACKNOWLEDGMENT</h2>
      <p><strong>STATE OF {{state}}</strong></p>
      <p><strong>COUNTY OF {{county}}</strong></p>
      <br/>
      <p>On this <strong>{{date}}</strong>, before me, <strong>{{notary_name}}</strong>, a Notary Public in and for said State, personally appeared <strong>{{signer_name}}</strong>, known to me (or proved to me on the basis of satisfactory evidence) to be the person(s) whose name(s) is/are subscribed to the within instrument and acknowledged to me that he/she/they executed the same in his/her/their authorized capacity(ies), and that by his/her/their signature(s) on the instrument the person(s), or the entity upon behalf of which the person(s) acted, executed the instrument.</p>
      <br/>
      <p>IN WITNESS WHEREOF, I have hereunto set my hand and official seal.</p>
      <br/><br/>
      <p>____________________________________</p>
      <p><strong>{{notary_name}}</strong>, Notary Public</p>
      <p>State of {{state}}</p>
      <p>Commission #: {{commission_number}}</p>
      <p>My Commission Expires: {{commission_expiration}}</p>
      ${DISCLAIMER}
    </div>`,
  },
  jurat: {
    id: "jurat",
    name: "Jurat Certificate",
    category: "Notarial Certificates",
    description: "Standard jurat (sworn/affirmed) certificate per ORC §147.55",
    placeholders: ["state", "county", "date", "signer_name", "notary_name", "commission_number", "commission_expiration"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">JURAT</h2>
      <p><strong>STATE OF {{state}}</strong></p>
      <p><strong>COUNTY OF {{county}}</strong></p>
      <br/>
      <p>Subscribed and sworn to (or affirmed) before me on this <strong>{{date}}</strong>, by <strong>{{signer_name}}</strong>, proved to me on the basis of satisfactory evidence to be the person(s) who appeared before me.</p>
      <br/><br/>
      <p>____________________________________</p>
      <p><strong>{{notary_name}}</strong>, Notary Public</p>
      <p>State of {{state}}</p>
      <p>Commission #: {{commission_number}}</p>
      <p>My Commission Expires: {{commission_expiration}}</p>
      ${DISCLAIMER}
    </div>`,
  },
  copy_certification: {
    id: "copy_certification",
    name: "Copy Certification",
    category: "Notarial Certificates",
    description: "Certification of a true copy of a document",
    placeholders: ["state", "county", "date", "document_description", "notary_name", "commission_number", "commission_expiration"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">CERTIFICATION OF COPY</h2>
      <p><strong>STATE OF {{state}}</strong></p>
      <p><strong>COUNTY OF {{county}}</strong></p>
      <br/>
      <p>I, <strong>{{notary_name}}</strong>, a Notary Public in and for the State of {{state}}, do hereby certify that on <strong>{{date}}</strong>, I was presented with the original of the following document: <strong>{{document_description}}</strong>.</p>
      <p>I further certify that the attached copy is a true, exact, complete, and unaltered photocopy of the original document.</p>
      <br/><br/>
      <p>____________________________________</p>
      <p><strong>{{notary_name}}</strong>, Notary Public</p>
      <p>Commission #: {{commission_number}}</p>
      <p>My Commission Expires: {{commission_expiration}}</p>
      ${DISCLAIMER}
    </div>`,
  },
  corporate_resolution: {
    id: "corporate_resolution",
    name: "Corporate Resolution",
    category: "Corporate",
    description: "Board resolution template for corporate actions",
    placeholders: ["company_name", "date", "resolution_text", "secretary_name", "president_name"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">CORPORATE RESOLUTION</h2>
      <h3 style="text-align:center;">{{company_name}}</h3>
      <br/>
      <p>At a duly called meeting of the Board of Directors of <strong>{{company_name}}</strong>, held on <strong>{{date}}</strong>, at which a quorum was present, the following resolution was adopted:</p>
      <br/>
      <p style="padding:16px;border-left:3px solid #333;margin:16px 0;"><strong>RESOLVED:</strong> {{resolution_text}}</p>
      <br/>
      <p>The undersigned hereby certifies that the foregoing is a true and correct copy of the resolution duly adopted by the Board of Directors.</p>
      <br/><br/>
      <p>____________________________________</p>
      <p><strong>{{secretary_name}}</strong>, Secretary</p>
      <br/>
      <p>____________________________________</p>
      <p><strong>{{president_name}}</strong>, President</p>
      ${DISCLAIMER}
    </div>`,
  },
  lien_waiver_conditional: {
    id: "lien_waiver_conditional",
    name: "Conditional Lien Waiver",
    category: "Construction",
    description: "Conditional waiver and release upon progress payment",
    placeholders: ["project_name", "property_address", "owner_name", "claimant_name", "amount", "through_date", "date"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">CONDITIONAL WAIVER AND RELEASE ON PROGRESS PAYMENT</h2>
      <p><strong>Project:</strong> {{project_name}}</p>
      <p><strong>Property Address:</strong> {{property_address}}</p>
      <p><strong>Owner:</strong> {{owner_name}}</p>
      <p><strong>Claimant:</strong> {{claimant_name}}</p>
      <br/>
      <p>Upon receipt of the sum of <strong>\${{amount}}</strong> for labor, services, equipment, or material furnished through <strong>{{through_date}}</strong>, the undersigned waives and releases any mechanic's lien, stop payment notice, or bond right the undersigned has on the above-referenced project to the following extent:</p>
      <p>This waiver covers payment only through the date stated above and only to the extent of the amount stated. All rights are reserved for amounts not yet received and for retainage.</p>
      <br/>
      <p><strong>NOTICE:</strong> This document waives rights unconditionally and states that you have been paid for giving up those rights. It is not the same as a receipt.</p>
      <br/><br/>
      <p>____________________________________</p>
      <p><strong>{{claimant_name}}</strong></p>
      <p>Date: {{date}}</p>
      ${DISCLAIMER}
    </div>`,
  },
  lien_waiver_unconditional: {
    id: "lien_waiver_unconditional",
    name: "Unconditional Lien Waiver",
    category: "Construction",
    description: "Unconditional waiver and release upon final payment",
    placeholders: ["project_name", "property_address", "owner_name", "claimant_name", "amount", "date"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">UNCONDITIONAL WAIVER AND RELEASE ON FINAL PAYMENT</h2>
      <p><strong>Project:</strong> {{project_name}}</p>
      <p><strong>Property Address:</strong> {{property_address}}</p>
      <p><strong>Owner:</strong> {{owner_name}}</p>
      <p><strong>Claimant:</strong> {{claimant_name}}</p>
      <br/>
      <p>The undersigned has been paid and has received a final payment in the sum of <strong>\${{amount}}</strong> for all labor, services, equipment, and material furnished on the above-referenced project, and does hereby waive and release any right to a mechanic's lien, stop payment notice, or any right against a labor and material bond on the project.</p>
      <br/><br/>
      <p>____________________________________</p>
      <p><strong>{{claimant_name}}</strong></p>
      <p>Date: {{date}}</p>
      ${DISCLAIMER}
    </div>`,
  },
  apostille_cover_letter: {
    id: "apostille_cover_letter",
    name: "Apostille Cover Letter",
    category: "Apostille",
    description: "Cover letter for apostille submission to Secretary of State",
    placeholders: ["sos_name", "sos_address", "sender_name", "sender_address", "document_count", "document_description", "destination_country", "fee_total", "date"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <p style="text-align:right;">{{date}}</p>
      <br/>
      <p>{{sos_name}}<br/>{{sos_address}}</p>
      <br/>
      <p>RE: Request for Apostille — {{document_count}} Document(s)</p>
      <br/>
      <p>Dear Sir or Madam,</p>
      <br/>
      <p>Enclosed please find <strong>{{document_count}}</strong> document(s) for apostille authentication:</p>
      <p style="padding:8px 16px;background:#f5f5f5;">{{document_description}}</p>
      <br/>
      <p>These documents are intended for use in <strong>{{destination_country}}</strong>.</p>
      <p>Enclosed is payment of <strong>\${{fee_total}}</strong> for the apostille fee(s).</p>
      <br/>
      <p>Please return the apostilled documents to:</p>
      <p><strong>{{sender_name}}</strong><br/>{{sender_address}}</p>
      <br/>
      <p>Thank you for your prompt attention to this request.</p>
      <br/>
      <p>Sincerely,</p>
      <br/><br/>
      <p>____________________________________</p>
      <p><strong>{{sender_name}}</strong></p>
      ${DISCLAIMER}
    </div>`,
  },
  trust_schedule_a: {
    id: "trust_schedule_a",
    name: "Trust Schedule A",
    category: "Estate Planning",
    description: "Schedule A - Property assigned to the trust",
    placeholders: ["trust_name", "grantor_name", "trustee_name", "date_established", "assets_html"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">SCHEDULE A</h2>
      <h3 style="text-align:center;">Property of the {{trust_name}}</h3>
      <br/>
      <p><strong>Grantor:</strong> {{grantor_name}}</p>
      <p><strong>Trustee:</strong> {{trustee_name}}</p>
      <p><strong>Date Established:</strong> {{date_established}}</p>
      <br/>
      <p>The following property is hereby assigned, transferred, and conveyed to the Trustee to be held, administered, and distributed in accordance with the terms of the Trust Agreement:</p>
      <br/>
      {{assets_html}}
      <br/>
      <p>____________________________________</p>
      <p><strong>{{grantor_name}}</strong>, Grantor</p>
      <br/>
      <p>____________________________________</p>
      <p><strong>{{trustee_name}}</strong>, Trustee</p>
      ${DISCLAIMER}
    </div>`,
  },
  affidavit_translation: {
    id: "affidavit_translation",
    name: "Translation Affidavit",
    category: "Immigration",
    description: "Affidavit of translation accuracy for USCIS submissions",
    placeholders: ["translator_name", "language", "document_description", "date", "state", "county", "notary_name", "commission_number", "commission_expiration"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">AFFIDAVIT OF TRANSLATION</h2>
      <p><strong>STATE OF {{state}}</strong></p>
      <p><strong>COUNTY OF {{county}}</strong></p>
      <br/>
      <p>I, <strong>{{translator_name}}</strong>, hereby certify under penalty of perjury that I am fluent in both English and <strong>{{language}}</strong>, and that the attached translation of the document described as <strong>{{document_description}}</strong> is a true and accurate translation from {{language}} to English, to the best of my knowledge and ability.</p>
      <br/>
      <p>____________________________________</p>
      <p><strong>{{translator_name}}</strong></p>
      <p>Date: {{date}}</p>
      <br/>
      <hr/>
      <p><em>Sworn to and subscribed before me on {{date}}.</em></p>
      <br/>
      <p>____________________________________</p>
      <p><strong>{{notary_name}}</strong>, Notary Public</p>
      <p>Commission #: {{commission_number}}</p>
      <p>My Commission Expires: {{commission_expiration}}</p>
      ${DISCLAIMER}
    </div>`,
  },
  odometer_disclosure: {
    id: "odometer_disclosure",
    name: "Odometer Disclosure Statement",
    category: "Auto/Fleet",
    description: "Federal odometer disclosure for vehicle title transfer",
    placeholders: ["vin", "year", "make", "model", "odometer_reading", "seller_name", "buyer_name", "date"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">ODOMETER DISCLOSURE STATEMENT</h2>
      <h4 style="text-align:center;">(Federal & State Requirements)</h4>
      <br/>
      <table style="width:100%;border-collapse:collapse;margin:16px 0;">
        <tr><td style="padding:8px;border:1px solid #ccc;width:40%;"><strong>VIN:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{vin}}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ccc;"><strong>Year:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{year}}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ccc;"><strong>Make:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{make}}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ccc;"><strong>Model:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{model}}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ccc;"><strong>Odometer Reading:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{odometer_reading}} miles</td></tr>
      </table>
      <br/>
      <p>I, <strong>{{seller_name}}</strong> (Seller/Transferor), hereby state that the odometer of the above-described vehicle now reads {{odometer_reading}} miles and to the best of my knowledge reflects the actual mileage of the vehicle.</p>
      <br/>
      <p>____________________________________</p>
      <p><strong>{{seller_name}}</strong>, Seller</p>
      <br/>
      <p>____________________________________</p>
      <p><strong>{{buyer_name}}</strong>, Buyer</p>
      <p>Date: {{date}}</p>
      ${DISCLAIMER}
    </div>`,
  },
  boi_report: {
    id: "boi_report",
    name: "BOI Report",
    category: "Corporate Compliance",
    description: "Beneficial Ownership Information report template",
    placeholders: ["company_name", "jurisdiction", "ein", "formation_date", "beneficial_owners_html", "date"],
    html: `<div style="font-family:serif;max-width:700px;margin:0 auto;padding:40px;">
      {{brand_header}}
      <h2 style="text-align:center;margin-bottom:24px;">BENEFICIAL OWNERSHIP INFORMATION REPORT</h2>
      <br/>
      <h3>Company Information</h3>
      <table style="width:100%;border-collapse:collapse;margin:16px 0;">
        <tr><td style="padding:8px;border:1px solid #ccc;width:40%;"><strong>Company Name:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{company_name}}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ccc;"><strong>Jurisdiction:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{jurisdiction}}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ccc;"><strong>EIN:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{ein}}</td></tr>
        <tr><td style="padding:8px;border:1px solid #ccc;"><strong>Formation Date:</strong></td><td style="padding:8px;border:1px solid #ccc;">{{formation_date}}</td></tr>
      </table>
      <br/>
      <h3>Beneficial Owners</h3>
      {{beneficial_owners_html}}
      <br/>
      <p>Report prepared on: {{date}}</p>
      ${DISCLAIMER}
    </div>`,
  },
};

export function getTemplatesByCategory(): Record<string, DocumentTemplate[]> {
  const result: Record<string, DocumentTemplate[]> = {};
  Object.values(documentTemplates).forEach((t) => {
    if (!result[t.category]) result[t.category] = [];
    result[t.category].push(t);
  });
  return result;
}
