/**
 * B-001+: Additional service registry entries for services that exist
 * in the DB but aren't in the core registry. These extend SERVICE_REGISTRY.
 */
import type { ServiceRegistryEntry } from "@/lib/serviceRegistry";

export const EXTENDED_SERVICES: ServiceRegistryEntry[] = [
  // Process Serving
  {
    id: "process-serving",
    name: "Process Serving",
    slug: "process-serving",
    category: "legal_support",
    description: "Professional service of process for legal documents",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "caseNumber", "serveeInfo"],
    tags: ["in-person", "rush-available"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 60,
  },
  // Document Translation
  {
    id: "document-translation",
    name: "Document Translation",
    slug: "document-translation",
    category: "document_services",
    description: "Certified document translation services",
    path: "/request",
    requiredFields: ["fullName", "email", "sourceLanguage", "targetLanguage", "documentType"],
    tags: ["remote", "rush-available", "nationwide"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 0, // async
  },
  // Background Checks
  {
    id: "background-check",
    name: "Background Check Coordination",
    slug: "background-check",
    category: "verification",
    description: "Fingerprinting and background check coordination services",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "checkType", "purpose"],
    tags: ["in-person", "id-required"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: true,
    estimatedDuration: 30,
  },
  // Fingerprinting
  {
    id: "fingerprinting",
    name: "Fingerprinting Services",
    slug: "fingerprinting",
    category: "verification",
    description: "Live Scan and ink fingerprinting services",
    path: "/book",
    requiredFields: ["fullName", "email", "phone", "scheduledDate", "scheduledTime"],
    tags: ["in-person", "id-required", "same-day"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: true,
    estimatedDuration: 15,
  },
  // Courier / Document Delivery
  {
    id: "courier-service",
    name: "Courier & Document Delivery",
    slug: "courier-service",
    category: "document_services",
    description: "Secure document pickup and delivery with chain of custody",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "pickupAddress", "dropoffAddress"],
    tags: ["in-person", "rush-available"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 60,
  },
  // Registered Agent
  {
    id: "registered-agent",
    name: "Registered Agent Service",
    slug: "registered-agent",
    category: "business",
    description: "Ohio registered agent service for business entities",
    path: "/request",
    requiredFields: ["fullName", "email", "businessName", "entityType"],
    tags: ["remote", "subscription"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 0, // subscription
  },
  // Mediation
  {
    id: "mediation",
    name: "Mediation Services",
    slug: "mediation",
    category: "legal_support",
    description: "Professional mediation and dispute resolution",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "disputeType"],
    tags: ["remote", "in-person"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 120,
  },
  // Immigration Support
  {
    id: "immigration-support",
    name: "Immigration Document Support",
    slug: "immigration-support",
    category: "document_services",
    description: "USCIS form preparation, I-9 verification, and immigration document notarization",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "uscisFormType"],
    tags: ["remote", "in-person", "id-required"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: true,
    estimatedDuration: 45,
  },
  // Permit Filings
  {
    id: "permit-filing",
    name: "Permit Filing Assistance",
    slug: "permit-filing",
    category: "business",
    description: "Business permit and license filing assistance",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "permitType"],
    tags: ["remote", "ohio-only"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 30,
  },
  // Tax Referral
  {
    id: "tax-referral",
    name: "Tax Preparation Referral",
    slug: "tax-referral",
    category: "business",
    description: "Tax preparation referral and document coordination",
    path: "/request",
    requiredFields: ["fullName", "email", "phone"],
    tags: ["remote"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 0,
  },
  // Photography / Passport Photos
  {
    id: "passport-photo",
    name: "Passport & ID Photos",
    slug: "passport-photos",
    category: "verification",
    description: "Compliant passport and ID photos for applications",
    path: "/book",
    requiredFields: ["fullName", "email", "scheduledDate", "scheduledTime"],
    tags: ["in-person", "same-day"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 15,
  },
  // Closing Coordination
  {
    id: "closing-coordination",
    name: "Closing Coordination",
    slug: "closing-coordination",
    category: "notarization",
    description: "Full-service real estate closing coordination",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "propertyAddress", "closingDate"],
    tags: ["in-person", "notary-required"],
    requiresNotary: true,
    ronAvailable: false,
    idRequired: true,
    estimatedDuration: 90,
  },
  // Notary Training
  {
    id: "notary-training",
    name: "Notary Training & Education",
    slug: "notary-training",
    category: "consulting",
    description: "Ohio notary commission preparation and continuing education",
    path: "/request",
    requiredFields: ["fullName", "email"],
    tags: ["remote"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 0,
  },
  // Healthcare Directive
  {
    id: "healthcare-directive",
    name: "Healthcare Directive",
    slug: "healthcare-directive",
    category: "notarization",
    description: "Living will and healthcare power of attorney preparation and notarization",
    path: "/book",
    requiredFields: ["fullName", "email", "phone", "scheduledDate", "scheduledTime"],
    tags: ["remote", "in-person", "notary-required", "id-required"],
    requiresNotary: true,
    ronAvailable: true,
    idRequired: true,
    estimatedDuration: 45,
    orcReference: "ORC §1337.12",
  },
  // Scrivener / Document Signing Agent
  {
    id: "scrivener-services",
    name: "Scrivener Services",
    slug: "scrivener-services",
    category: "document_services",
    description: "Professional scrivener services for document reading and signing assistance",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "documentType"],
    tags: ["in-person"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 45,
  },
  // Insurance Coordination
  {
    id: "insurance-coordination",
    name: "Insurance Coordination",
    slug: "insurance-coordination",
    category: "business",
    description: "Notary E&O insurance coordination and compliance review",
    path: "/request",
    requiredFields: ["fullName", "email"],
    tags: ["remote"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 30,
  },
  // Compliance Calendar
  {
    id: "compliance-calendar",
    name: "Compliance Calendar Service",
    slug: "compliance-calendar",
    category: "compliance",
    description: "Automated compliance deadline tracking and renewal reminders",
    path: "/request",
    requiredFields: ["fullName", "email", "entityName"],
    tags: ["remote", "subscription"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 0,
  },
  // Construction Draw Inspections
  {
    id: "construction-draw",
    name: "Construction Draw Inspection",
    slug: "construction-draw-inspection",
    category: "real_estate",
    description: "On-site construction progress verification and draw release certification",
    path: "/request",
    requiredFields: ["fullName", "email", "phone", "projectAddress", "contractorName"],
    tags: ["in-person"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 60,
  },
  // Recorder/SOS Filings
  {
    id: "recorder-filings",
    name: "County Recorder Filings",
    slug: "county-recorder-filings",
    category: "legal_support",
    description: "Document recording with Ohio county recorders and Secretary of State",
    path: "/request",
    requiredFields: ["fullName", "email", "county", "documentType"],
    tags: ["ohio-only", "rush-available"],
    requiresNotary: false,
    ronAvailable: false,
    idRequired: false,
    estimatedDuration: 30,
  },
];
