/**
 * CO-007: Public accessibility statement page component
 */
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SEOHead } from "@/components/SEOHead";

export function AccessibilityStatement() {
  return (
    <>
      <SEOHead
        title="Accessibility Statement"
        description="NotaryDex is committed to ensuring digital accessibility for people with disabilities."
      />
      <div className="container max-w-3xl mx-auto py-12 px-4">
        <Card>
          <CardHeader>
            <CardTitle className="text-2xl">Accessibility Statement</CardTitle>
          </CardHeader>
          <CardContent className="prose prose-sm dark:prose-invert max-w-none space-y-4">
            <p>
              NotaryDex is committed to ensuring digital accessibility for people with disabilities.
              We are continually improving the user experience for everyone and applying the relevant
              accessibility standards.
            </p>

            <h3>Conformance Status</h3>
            <p>
              We aim to conform to the Web Content Accessibility Guidelines (WCAG) 2.1 at Level AA.
              These guidelines explain how to make web content more accessible for people with disabilities
              and more user-friendly for everyone.
            </p>

            <h3>Measures Taken</h3>
            <ul>
              <li>Semantic HTML structure with proper heading hierarchy</li>
              <li>Keyboard navigation support throughout the application</li>
              <li>ARIA labels and roles for interactive elements</li>
              <li>Sufficient color contrast ratios (minimum 4.5:1 for text)</li>
              <li>Focus indicators for all interactive elements</li>
              <li>Alt text for all informative images</li>
              <li>Responsive design that supports zoom up to 200%</li>
              <li>Skip-to-content link for keyboard users</li>
              <li>Reduced motion support via <code>prefers-reduced-motion</code></li>
            </ul>

            <h3>Known Limitations</h3>
            <ul>
              <li>Some third-party embedded content (maps, payment forms) may have limited accessibility</li>
              <li>PDF documents generated by the platform may not be fully screen-reader accessible</li>
              <li>Real-time video features (RON sessions) require audio/video capability</li>
            </ul>

            <h3>Feedback & Contact</h3>
            <p>
              We welcome your feedback on the accessibility of NotaryDex. If you encounter
              accessibility barriers, please contact us:
            </p>
            <ul>
              <li>Email: <a href="mailto:shane@notardex.com" className="text-primary">shane@notardex.com</a></li>
              <li>Phone: <a href="tel:+16143006890" className="text-primary">(614) 300-6890</a></li>
            </ul>
            <p>We aim to respond to accessibility feedback within 3 business days.</p>

            <h3>Assessment Methods</h3>
            <p>
              NotaryDex assesses the accessibility of our platform through automated testing
              (axe-core), manual keyboard testing, and screen reader testing with NVDA and VoiceOver.
            </p>

            <p className="text-sm text-muted-foreground mt-6">
              This statement was last updated on {new Date().toLocaleDateString()}.
            </p>
          </CardContent>
        </Card>
      </div>
    </>
  );
}
