export type PageEntry = {
  route: string;
  component: string;
  protection: "public" | "auth" | "admin";
  category: string;
};

export const PAGE_REGISTRY: PageEntry[] = [
  // Public pages
  { route: "/", component: "Index", protection: "public", category: "Marketing" },
  { route: "/coming-soon", component: "ComingSoon", protection: "public", category: "Marketing" },
  { route: "/login", component: "Login", protection: "public", category: "Auth" },
  { route: "/signup", component: "SignUp", protection: "public", category: "Auth" },
  { route: "/reset-password", component: "ForgotPassword", protection: "public", category: "Auth" },
  { route: "/book", component: "BookAppointment", protection: "public", category: "Booking" },
  { route: "/notary-guide", component: "NotaryGuide", protection: "public", category: "Content" },
  { route: "/ron-info", component: "RonInfo", protection: "public", category: "Content" },
  { route: "/services", component: "Services", protection: "public", category: "Marketing" },
  { route: "/services/:serviceId", component: "ServiceDetail", protection: "public", category: "Marketing" },
  { route: "/ron-check", component: "RonEligibilityChecker", protection: "public", category: "Tools" },
  { route: "/loan-signing", component: "LoanSigningServices", protection: "public", category: "Marketing" },
  { route: "/verify/:id", component: "VerifySeal", protection: "public", category: "Verification" },
  { route: "/terms", component: "TermsPrivacy", protection: "public", category: "Legal" },
  { route: "/templates", component: "DocumentTemplates", protection: "public", category: "Content" },
  { route: "/about", component: "About", protection: "public", category: "Marketing" },
  { route: "/join", component: "JoinPlatform", protection: "public", category: "Marketing" },
  { route: "/notary-guide-process", component: "NotaryProcessGuide", protection: "public", category: "Content" },
  { route: "/unsubscribe", component: "Unsubscribe", protection: "public", category: "Email" },
  { route: "/maintenance", component: "Maintenance", protection: "public", category: "System" },
  { route: "/fee-calculator", component: "FeeCalculator", protection: "public", category: "Tools" },
  { route: "/resources", component: "Resources", protection: "public", category: "Content" },
  { route: "/help", component: "HelpSupport", protection: "public", category: "Content" },
  { route: "/solutions/notaries", component: "ForNotaries", protection: "public", category: "Solutions" },
  { route: "/solutions/hospitals", component: "ForHospitals", protection: "public", category: "Solutions" },
  { route: "/solutions/real-estate", component: "ForRealEstate", protection: "public", category: "Solutions" },
  { route: "/solutions/law-firms", component: "ForLawFirms", protection: "public", category: "Solutions" },
  { route: "/solutions/small-business", component: "ForSmallBusiness", protection: "public", category: "Solutions" },
  { route: "/solutions/individuals", component: "ForIndividuals", protection: "public", category: "Solutions" },

  // Auth-protected pages
  { route: "/portal", component: "ClientPortal", protection: "auth", category: "Client Portal" },
  { route: "/business-portal", component: "BusinessPortal", protection: "auth", category: "Business Portal" },
  { route: "/confirmation", component: "AppointmentConfirmation", protection: "auth", category: "Booking" },
  { route: "/ron-session", component: "RonSession", protection: "auth", category: "RON" },
  { route: "/digitize", component: "DocumentDigitize", protection: "auth", category: "AI Tools" },
  { route: "/request", component: "ServiceRequest", protection: "auth", category: "Services" },
  { route: "/mailroom", component: "VirtualMailroom", protection: "auth", category: "Services" },
  { route: "/subscribe", component: "SubscriptionPlans", protection: "auth", category: "Billing" },
  { route: "/verify-id", component: "VerifyIdentity", protection: "auth", category: "RON" },
  { route: "/mobile-upload", component: "MobileUpload", protection: "auth", category: "Documents" },
  { route: "/builder", component: "DocumentBuilder", protection: "auth", category: "AI Tools" },
  { route: "/ai-writer", component: "AIWriter", protection: "auth", category: "AI Tools" },
  { route: "/ai-extractors", component: "AIExtractors", protection: "auth", category: "AI Tools" },
  { route: "/ai-knowledge", component: "AIKnowledge", protection: "auth", category: "AI Tools" },
  { route: "/account-settings", component: "AccountSettings", protection: "auth", category: "Settings" },

  // Admin pages
  { route: "/admin", component: "AdminOverview", protection: "admin", category: "Admin" },
  { route: "/admin/appointments", component: "AdminAppointments", protection: "admin", category: "Admin" },
  { route: "/admin/clients", component: "AdminClients", protection: "admin", category: "Admin" },
  { route: "/admin/availability", component: "AdminAvailability", protection: "admin", category: "Admin" },
  { route: "/admin/documents", component: "AdminDocuments", protection: "admin", category: "Admin" },
  { route: "/admin/journal", component: "AdminJournal", protection: "admin", category: "Admin" },
  { route: "/admin/revenue", component: "AdminRevenue", protection: "admin", category: "Admin" },
  { route: "/admin/templates", component: "AdminTemplates", protection: "admin", category: "Admin" },
  { route: "/admin/apostille", component: "AdminApostille", protection: "admin", category: "Admin" },
  { route: "/admin/chat", component: "AdminChat", protection: "admin", category: "Admin" },
  { route: "/admin/business-clients", component: "AdminBusinessClients", protection: "admin", category: "Admin" },
  { route: "/admin/services", component: "AdminServices", protection: "admin", category: "Admin" },
  { route: "/admin/resources", component: "AdminResources", protection: "admin", category: "Admin" },
  { route: "/admin/ai-assistant", component: "AdminAIAssistant", protection: "admin", category: "Admin" },
  { route: "/admin/audit-log", component: "AdminAuditLog", protection: "admin", category: "Admin" },
  { route: "/admin/team", component: "AdminTeam", protection: "admin", category: "Admin" },
  { route: "/admin/email-management", component: "AdminEmailManagement", protection: "admin", category: "Admin" },
  { route: "/admin/leads", component: "AdminLeadPortal", protection: "admin", category: "Admin" },
  { route: "/admin/users", component: "AdminUsers", protection: "admin", category: "Admin" },
  { route: "/admin/service-requests", component: "AdminServiceRequests", protection: "admin", category: "Admin" },
  { route: "/admin/content-workspace", component: "AdminContentWorkspace", protection: "admin", category: "Admin" },
  { route: "/admin/task-queue", component: "AdminTaskQueue", protection: "admin", category: "Admin" },
  { route: "/admin/crm", component: "AdminCRM", protection: "admin", category: "Admin" },
  { route: "/admin/build-tracker", component: "AdminBuildTracker", protection: "admin", category: "Admin" },
  { route: "/admin/settings", component: "AdminSettings", protection: "admin", category: "Admin" },
  { route: "/admin/integrations", component: "AdminIntegrationTest", protection: "admin", category: "Admin" },
];
