export type EntityStatus = "healthy" | "needs_attention" | "partial" | "missing";

export type SubComponent = {
  name: string;
  status: EntityStatus;
  route?: string;
  edgeFunction?: string;
  description: string;
};

export type PlatformEntity = {
  id: string;
  name: string;
  icon: string;
  domain: string;
  description: string;
  subComponents: SubComponent[];
};

export const PLATFORM_ENTITIES: PlatformEntity[] = [
  {
    id: "email-management",
    name: "Email Management",
    icon: "Mail",
    domain: "Communication",
    description: "IONOS IMAP/SMTP sync, automated emails, templates, deliverability",
    subComponents: [
      { name: "IONOS IMAP Sync", status: "healthy", edgeFunction: "ionos-email-sync", description: "Background email synchronization" },
      { name: "Email Compose/Send", status: "healthy", route: "/admin/email-management", description: "Rich text email composer" },
      { name: "Email Templates", status: "healthy", route: "/admin/settings", description: "Branded email template designer" },
      { name: "Auth Email Hook", status: "healthy", edgeFunction: "auth-email-hook", description: "Custom auth email delivery" },
      { name: "Appointment Emails", status: "healthy", edgeFunction: "send-appointment-emails", description: "Booking confirmations" },
      { name: "Reminder Emails", status: "healthy", edgeFunction: "send-appointment-reminders", description: "24hr/30min reminders" },
      { name: "Email Queue (pgmq)", status: "healthy", edgeFunction: "process-email-queue", description: "Durable queue with retry/DLQ" },
      { name: "Signature Management", status: "healthy", description: "Custom email signatures (email_signatures table)" },
      { name: "Client Correspondence", status: "healthy", route: "/admin/client-emails", edgeFunction: "send-correspondence", description: "Threaded client communications" },
      { name: "Inbound Email Processing", status: "healthy", edgeFunction: "process-inbound-email", description: "Auto-route inbound emails to clients" },
      { name: "IONOS Email Integration", status: "healthy", edgeFunction: "ionos-email", description: "IONOS SMTP send endpoint" },
      { name: "Email Send Log", status: "healthy", description: "Delivery tracking (email_send_log table)" },
      { name: "Email Cache", status: "healthy", description: "Synced email storage (email_cache table)" },
      { name: "Email Drafts", status: "healthy", description: "Saved draft emails (email_drafts table)" },
      { name: "Email Send State", status: "healthy", description: "Queue config & rate control (email_send_state table)" },
      { name: "Unsubscribe Tokens", status: "healthy", description: "One-click unsubscribe (email_unsubscribe_tokens table)" },
      { name: "Appointment Email Log", status: "healthy", description: "Sent appointment emails (appointment_emails table)" },
    ],
  },
  {
    id: "services-catalog",
    name: "Services Catalog",
    icon: "BookOpen",
    domain: "Core Business",
    description: "14+ service categories with fuzzy search, detail pages, pricing",
    subComponents: [
      { name: "Service Listing Page", status: "healthy", route: "/services", description: "Filterable service catalog" },
      { name: "Service Detail Pages", status: "healthy", route: "/services/:slug", description: "Category-specific FAQs & checklists" },
      { name: "Service Constants", status: "healthy", description: "Centralized service definitions (serviceConstants.ts)" },
      { name: "Fee Calculator", status: "healthy", route: "/fee-calculator", description: "Dynamic pricing engine" },
      { name: "Service Pre-Qualifier", status: "healthy", description: "Readiness assessment widget" },
      { name: "Service Requests", status: "healthy", route: "/service-request", description: "Intake-only request module" },
      { name: "Admin Services", status: "healthy", route: "/admin/services", description: "Service catalog management" },
      { name: "Admin Service Requests", status: "healthy", route: "/admin/service-requests", description: "Request review & assignment" },
      { name: "Loan Signing Services", status: "healthy", route: "/loan-signing", description: "Specialized loan signing page" },
      { name: "Service Reviews", status: "healthy", description: "Client reviews (service_reviews table)" },
      { name: "Service FAQs", status: "healthy", description: "Per-service FAQ entries (service_faqs table)" },
      { name: "Service Requirements", status: "healthy", description: "Service prerequisite rules (service_requirements table)" },
      { name: "Service Workflows", status: "partial", description: "Workflow definitions (service_workflows table)" },
    ],
  },
  {
    id: "appointments",
    name: "Appointments & Scheduling",
    icon: "Calendar",
    domain: "Core Business",
    description: "Booking flow, scheduling, reminders, rescheduling, calendar",
    subComponents: [
      { name: "Booking Wizard", status: "healthy", route: "/book", description: "Multi-step appointment booking" },
      { name: "Schedule Step", status: "healthy", description: "Date/time selection with availability" },
      { name: "Intake Fields", status: "healthy", description: "Signer details & document info" },
      { name: "Review & Confirm", status: "healthy", description: "Pre-submission review" },
      { name: "Confirmation Page", status: "healthy", route: "/confirmation", description: "Post-booking confirmation" },
      { name: "Calendar Download", status: "healthy", description: "ICS/Google Calendar export" },
      { name: "Double-Booking Prevention", status: "healthy", description: "DB trigger prevents conflicts" },
      { name: "Past Date Validation", status: "healthy", description: "DB trigger blocks past dates" },
      { name: "Draft Persistence", status: "healthy", description: "Save in-progress bookings (booking_drafts table)" },
      { name: "Admin Appointments", status: "healthy", route: "/admin/appointments", description: "Manage all appointments" },
      { name: "Availability Calendar", status: "healthy", route: "/admin/availability", description: "Set notary availability" },
      { name: "Recurrence Rules", status: "partial", description: "Recurring appointment support" },
      { name: "Time Slots", status: "healthy", description: "Available time slots (time_slots table)" },
    ],
  },
  {
    id: "payments",
    name: "Payments & Billing",
    icon: "CreditCard",
    domain: "Financial",
    description: "Stripe integration, invoicing, receipts, promo codes",
    subComponents: [
      { name: "Stripe Payment Form", status: "healthy", description: "Embedded payment collection" },
      { name: "Payment Intent Creation", status: "healthy", edgeFunction: "create-payment-intent", description: "Server-side Stripe intent" },
      { name: "Stripe Webhooks", status: "healthy", edgeFunction: "stripe-webhook", description: "Payment event processing" },
      { name: "Stripe Config", status: "healthy", edgeFunction: "get-stripe-config", description: "Publishable key endpoint" },
      { name: "Invoice Generator", status: "healthy", description: "Post-session invoice creation" },
      { name: "Revenue Dashboard", status: "healthy", route: "/admin/revenue", description: "Financial analytics" },
      { name: "Subscription Plans", status: "partial", route: "/plans", description: "Recurring subscription management" },
      { name: "Payments Table", status: "healthy", description: "Payment records (payments table)" },
      { name: "Promo Codes", status: "partial", description: "Discount code system (promo_codes table)" },
      { name: "Notary Payouts", status: "healthy", description: "Notary compensation tracking (notary_payouts table)" },
      { name: "Refund Processing", status: "needs_attention", description: "Manual refund workflow" },
    ],
  },
  {
    id: "documents",
    name: "Document Management",
    icon: "FileText",
    domain: "Core Business",
    description: "Upload, OCR, templates, versioning, e-seal verification",
    subComponents: [
      { name: "Document Upload", status: "healthy", description: "Client portal upload" },
      { name: "Bulk Upload", status: "healthy", description: "Multi-file drag & drop" },
      { name: "Mobile Upload", status: "healthy", route: "/mobile-upload", description: "Camera/file mobile upload" },
      { name: "Admin Document Review", status: "healthy", route: "/admin/documents", description: "Approve/reject documents" },
      { name: "Document Templates", status: "healthy", route: "/templates", description: "Pre-built notary templates" },
      { name: "Document Builder", status: "healthy", route: "/builder", description: "AI-powered doc creation" },
      { name: "OCR Digitization", status: "healthy", route: "/digitize", edgeFunction: "ocr-digitize", description: "Scan and extract text" },
      { name: "E-Seal Verification", status: "healthy", route: "/verify/:id", description: "Public document verification" },
      { name: "Tags & Collections", status: "healthy", description: "Document organization (document_tags, document_collections tables)" },
      { name: "Expiry Reminders", status: "healthy", description: "Automated expiry alerts (document_reminders table)" },
      { name: "Version History", status: "healthy", description: "Document version tracking (document_versions table)" },
      { name: "Document Bundles", status: "healthy", description: "Pre-defined document bundles (document_bundles table)" },
      { name: "Form Library", status: "healthy", description: "Reusable form templates (form_library table)" },
      { name: "Document Explanation", status: "healthy", edgeFunction: "explain-document", description: "AI document explanation" },
      { name: "Document Detection", status: "healthy", edgeFunction: "detect-document", description: "AI document classification" },
      { name: "Document Translation", status: "healthy", edgeFunction: "translate-document", description: "AI-powered translation" },
    ],
  },
  {
    id: "ron-sessions",
    name: "RON Sessions",
    icon: "Video",
    domain: "Compliance",
    description: "Remote Online Notarization per Ohio ORC §147.66",
    subComponents: [
      { name: "Tech Check", status: "healthy", route: "/ron-session", description: "Camera/mic/browser check" },
      { name: "Identity Verification", status: "healthy", route: "/verify-id", description: "ID scan + credential check" },
      { name: "ID Scan Assistant", status: "healthy", edgeFunction: "scan-id", description: "AI-powered ID scanning" },
      { name: "KBA Challenge", status: "healthy", description: "Knowledge-Based Auth (max 2 attempts)" },
      { name: "Recording Consent", status: "healthy", description: "Audio/video consent capture" },
      { name: "Signing Platform", status: "partial", description: "Manual mode works; API mode placeholder" },
      { name: "SignNow Integration", status: "partial", edgeFunction: "signnow", description: "SignNow e-signing API" },
      { name: "SignNow Webhooks", status: "healthy", edgeFunction: "signnow-webhook", description: "Signing event callbacks" },
      { name: "E-Seal Generation", status: "healthy", description: "Digital notary seal (e_seal_verifications table)" },
      { name: "Journal Entry Auto-Create", status: "healthy", description: "Ohio-compliant journal entry" },
      { name: "Session Tracking", status: "healthy", description: "Full session state (notarization_sessions table)" },
      { name: "Session Timeout (60min)", status: "healthy", description: "Auto-timeout inactive sessions" },
      { name: "Signer IP Capture", status: "healthy", description: "Ohio compliance requirement" },
      { name: "Location Attestation", status: "healthy", description: "Physical state recording" },
      { name: "Vital Records Block", status: "healthy", description: "Block birth/death certificates" },
      { name: "Session Timeout Warning", status: "healthy", description: "5-minute countdown alert" },
    ],
  },
  {
    id: "crm-leads",
    name: "CRM & Leads",
    icon: "Users",
    domain: "Sales",
    description: "Pipeline management, deal tracking, lead generation",
    subComponents: [
      { name: "Lead Portal", status: "healthy", route: "/admin/leads", description: "All leads with filtering" },
      { name: "CRM Pipeline", status: "healthy", route: "/admin/crm", description: "Deal stages & activities (deals, crm_activities tables)" },
      { name: "AI Chatbot Lead Capture", status: "healthy", description: "Conversational lead collection" },
      { name: "Email Lead Extraction", status: "healthy", edgeFunction: "extract-email-leads", description: "Auto-extract from emails" },
      { name: "Proposal Generation", status: "healthy", edgeFunction: "generate-lead-proposal", description: "AI-generated proposals" },
      { name: "Lead Sources Management", status: "healthy", description: "Multi-channel tracking (lead_sources table)" },
      { name: "Lead Discovery", status: "healthy", edgeFunction: "discover-leads", description: "AI lead discovery" },
      { name: "Lead Fetching", status: "healthy", edgeFunction: "fetch-leads", description: "Lead data retrieval" },
      { name: "Lead Submission", status: "healthy", edgeFunction: "submit-lead", description: "Public lead form endpoint" },
      { name: "Social Lead Scraping", status: "healthy", edgeFunction: "scrape-social-leads", description: "Social media lead discovery" },
      { name: "HubSpot Sync", status: "partial", edgeFunction: "hubspot-sync", description: "CRM synchronization (deferred per roadmap)" },
      { name: "Leads Table", status: "healthy", description: "Lead records (leads table)" },
    ],
  },
  {
    id: "client-portal",
    name: "Client Portal",
    icon: "LayoutDashboard",
    domain: "User Experience",
    description: "Authenticated client dashboard for managing services",
    subComponents: [
      { name: "Dashboard Overview", status: "healthy", route: "/portal", description: "Summary cards & quick actions" },
      { name: "Documents Tab", status: "healthy", description: "Upload/view/download documents" },
      { name: "Chat Tab", status: "healthy", description: "Real-time messaging (chat_messages table)" },
      { name: "Appointments Tab", status: "healthy", description: "View upcoming/past appointments" },
      { name: "Correspondence Tab", status: "healthy", description: "Formal correspondence (client_correspondence table)" },
      { name: "Service Requests Tab", status: "healthy", description: "Submit and track requests" },
      { name: "Progress Tracker", status: "healthy", description: "Visual timeline" },
      { name: "Account Settings", status: "healthy", route: "/account-settings", description: "Profile management" },
      { name: "Client Feedback", status: "healthy", description: "Post-appointment feedback (client_feedback table)" },
      { name: "User Favorites", status: "partial", description: "Bookmarked items (user_favorites table)" },
    ],
  },
  {
    id: "business-portal",
    name: "Business Portal",
    icon: "Building",
    domain: "User Experience",
    description: "Organization account management",
    subComponents: [
      { name: "Business Registration", status: "healthy", route: "/business-portal", description: "Create business profile (business_profiles table)" },
      { name: "Member Management", status: "healthy", description: "Add/remove authorized signers (business_members table)" },
      { name: "Business Documents", status: "healthy", description: "Organization documents" },
      { name: "Business Verification", status: "healthy", route: "/admin/business-clients", description: "Admin verification" },
    ],
  },
  {
    id: "admin-dashboard",
    name: "Admin Dashboard",
    icon: "Settings",
    domain: "Operations",
    description: "Administrative operations and management",
    subComponents: [
      { name: "Overview KPIs", status: "healthy", route: "/admin", description: "Key performance indicators" },
      { name: "Notary Journal", status: "healthy", route: "/admin/journal", description: "Ohio-compliant journal (notary_journal table)" },
      { name: "Revenue Analytics", status: "healthy", route: "/admin/revenue", description: "Financial dashboard" },
      { name: "Audit Log", status: "healthy", route: "/admin/audit-log", description: "System audit trail (audit_log table)" },
      { name: "Team Management", status: "healthy", route: "/admin/team", description: "Notary invites & roles (notary_invites, notary_certifications tables)" },
      { name: "Task Queue", status: "healthy", route: "/admin/task-queue", description: "Prioritized task management" },
      { name: "Content Workspace", status: "healthy", route: "/admin/content-workspace", description: "AI content creation" },
      { name: "Integration Hub", status: "healthy", route: "/admin/integrations", description: "Third-party services" },
      { name: "User Management", status: "healthy", route: "/admin/users", edgeFunction: "admin-create-user", description: "Create & manage users" },
      { name: "Platform Settings", status: "healthy", route: "/admin/settings", description: "Global platform config (platform_settings table)" },
      { name: "Continuing Education", status: "healthy", description: "CE credit tracking (continuing_education table)" },
    ],
  },
  {
    id: "ai-services",
    name: "AI Services",
    icon: "Brain",
    domain: "Intelligence",
    description: "AI-powered extraction, drafting, compliance, and analysis",
    subComponents: [
      { name: "Smart Extractors", status: "healthy", route: "/ai-extractors", edgeFunction: "ai-extract-document", description: "Legal/Finance/HR extraction" },
      { name: "Cross-Document Synthesis", status: "healthy", edgeFunction: "ai-cross-document", description: "RAG multi-document querying" },
      { name: "Compliance Watchdog", status: "healthy", edgeFunction: "ai-compliance-scan", description: "Real-time compliance auditing" },
      { name: "Style-Match Drafting", status: "healthy", edgeFunction: "ai-style-match", description: "Client-specific tone matching (client_style_profiles table)" },
      { name: "AI Writer", status: "healthy", route: "/ai-writer", description: "AI-powered content creation" },
      { name: "AI Knowledge Base", status: "healthy", route: "/ai-knowledge", description: "AI knowledge management" },
      { name: "Document Detection", status: "healthy", edgeFunction: "detect-document", description: "Auto-classify documents" },
      { name: "Client Assistant", status: "healthy", edgeFunction: "client-assistant", description: "AI chat for clients" },
      { name: "Notary Assistant", status: "healthy", edgeFunction: "notary-assistant", description: "AI chat for notaries" },
      { name: "Build Analyst", status: "healthy", edgeFunction: "build-analyst", description: "AI build analysis & planning" },
      { name: "ID Scan AI", status: "healthy", edgeFunction: "scan-id", description: "AI-powered ID document scanning" },
    ],
  },
  {
    id: "authentication",
    name: "Authentication & Security",
    icon: "Shield",
    domain: "Security",
    description: "User auth, roles, session management",
    subComponents: [
      { name: "Email/Password Auth", status: "healthy", route: "/login", description: "Standard authentication" },
      { name: "Signup Flow", status: "healthy", route: "/signup", description: "User registration" },
      { name: "Password Recovery", status: "healthy", route: "/forgot-password", description: "Password reset flow" },
      { name: "Role-Based Access", status: "healthy", description: "Admin/notary/client roles (user_roles table)" },
      { name: "Protected Routes", status: "healthy", description: "Route guard component" },
      { name: "User Profiles", status: "healthy", description: "User profile data (profiles table)" },
      { name: "Compliance Rule Sets", status: "healthy", description: "Configurable compliance rules (compliance_rule_sets table)" },
      { name: "MFA", status: "partial", description: "Multi-factor authentication (deferred per roadmap)" },
      { name: "Session Management", status: "healthy", description: "Auto-refresh tokens" },
    ],
  },
  {
    id: "notifications",
    name: "Notifications & Alerts",
    icon: "Bell",
    domain: "Communication",
    description: "Email reminders, session alerts, system notifications",
    subComponents: [
      { name: "Appointment Reminders", status: "healthy", description: "24hr/30min automated emails" },
      { name: "Session Timeout Warning", status: "healthy", description: "RON session countdown" },
      { name: "Document Expiry Alerts", status: "healthy", description: "Upcoming expiry notifications" },
      { name: "Admin Notification Center", status: "healthy", description: "In-app admin alerts" },
      { name: "Cookie Consent", status: "healthy", description: "GDPR compliance banner" },
      { name: "Compliance Banner", status: "healthy", description: "Ohio compliance notices" },
      { name: "Notification Preferences", status: "partial", description: "User notification settings (notification_preferences table)" },
    ],
  },
  {
    id: "mailroom",
    name: "Virtual Mailroom",
    icon: "Inbox",
    domain: "Services",
    description: "Physical mail scanning, forwarding, and management",
    subComponents: [
      { name: "Mailroom Dashboard", status: "healthy", route: "/mailroom", description: "Client mail overview" },
      { name: "Mail Item Tracking", status: "healthy", description: "Receive, scan, forward mail (mailroom_items table)" },
      { name: "Admin Mailroom", status: "healthy", route: "/admin/mailbox", description: "Admin mail management" },
    ],
  },
  {
    id: "apostille",
    name: "Apostille Services",
    icon: "Stamp",
    domain: "Services",
    description: "International document authentication via apostille",
    subComponents: [
      { name: "Apostille Requests", status: "healthy", description: "Client apostille submissions (apostille_requests table)" },
      { name: "Admin Apostille", status: "healthy", route: "/admin/apostille", description: "Manage apostille processing" },
      { name: "Tracking & Shipping", status: "healthy", description: "Shipping labels and tracking" },
    ],
  },
  {
    id: "solutions",
    name: "Solutions & Verticals",
    icon: "Target",
    domain: "Marketing",
    description: "Industry-specific landing pages for target audiences",
    subComponents: [
      { name: "For Notaries", status: "healthy", route: "/solutions/notaries", description: "Notary platform benefits" },
      { name: "For Hospitals", status: "healthy", route: "/solutions/hospitals", description: "Healthcare notary solutions" },
      { name: "For Real Estate", status: "healthy", route: "/solutions/real-estate", description: "Real estate closing services" },
      { name: "For Law Firms", status: "healthy", route: "/solutions/law-firms", description: "Legal notarization services" },
      { name: "For Small Business", status: "healthy", route: "/solutions/small-business", description: "Small business packages" },
      { name: "For Individuals", status: "healthy", route: "/solutions/individuals", description: "Personal notarization needs" },
    ],
  },
];

export function getEntityHealth(entity: PlatformEntity): { status: EntityStatus; healthPct: number } {
  const total = entity.subComponents.length;
  const healthy = entity.subComponents.filter(s => s.status === "healthy").length;
  const partial = entity.subComponents.filter(s => s.status === "partial").length;
  const needsAttention = entity.subComponents.filter(s => s.status === "needs_attention").length;
  const missing = entity.subComponents.filter(s => s.status === "missing").length;
  const pct = Math.round(((healthy + partial * 0.5) / total) * 100);

  if (missing > 0 || needsAttention > 2) return { status: "needs_attention", healthPct: pct };
  if (partial > 0 || needsAttention > 0) return { status: "partial", healthPct: pct };
  return { status: "healthy", healthPct: pct };
}
